site_name: CCSS Info and Docs
site_url: http://ccss.carleton.ca:8000
site_author: Carleton Computer Science Society
theme: readthedocs
repo_url: https://github.com/CarletonComputerScienceSociety/ccss-docs/
pages:
- Home: 'index.md'
- 'Contact Us': 'contact-us.md'
- Governance:
  - 'Overview': 'governance/Overview.md'
  - 'Constitution': 'governance/Constitution.md'
  - 'Rules of Operation': 'governance/Rules-of-Operation.md'
  - 'Meetings': 'governance/Meetings.md'
  - Directors:
    - 'President': 'governance/directors/president.md'
    - 'Vice-President': 'governance/directors/Vice-President.md'
    - 'Treasurer': 'governance/directors/Treasurer.md'
    - 'VP Academics': 'governance/directors/VP-of-Academics.md'
    - 'VP Social': 'governance/directors/VP-of-Social.md'
  - Officers:
    - 'Overview and Listing': 'governance/officers/Overview.md'
    - 'Officer of Society Outreach': 'governance/officers/Officer-of-Society-Outreach.md'
    - 'Officer of Systems Administration': 'governance/officers/Officer-of-Systems-Administration.md'
    - 'Officer of Lounge Management': 'governance/officers/Officer-of-Lounge-Management.md'
  - Committees:
    - 'Committees Information': 'governance/committees/Overview-of-Committees.md'
    - 'List of Committees': 'governance/committees/List-of-Committees.md'
- Resources:
  - 'Overview': 'resources/overview.md'
  - 'Lounge Services': 'resources/lounge.md'
  - 'Events Info': 'resources/events.md'
  - 'Partnered Clubs': 'resources/clubs.md'
  - 'Volunteering Info': 'resources/volunteering.md'
  - 'Work with the CCSS': 'resources/partnership.md'
- Student-Handbook:
  - Introduction:
    - 'Introduction': 'student-handbook/1-introduction/1-intro.md'
    - 'Getting to Know Your Acronyms': 'student-handbook/1-introduction/1-acronyms.md'
    - 'Referral Guide': 'student-handbook/1-introduction/referral-guide.md'
  - Academics:
    - 'What is an Elective?': 'student-handbook/2-academics/2-electives.md'
    - 'Top Five Best Electives': 'student-handbook/2-academics/2-best-electives.md'
    - 'Minors? What?': 'student-handbook/2-academics/2-minors.md'
    - 'What is so Honourable About Honours?': 'student-handbook/2-academics/2-honours.md'
    - 'Crossing the Streams': 'student-handbook/2-academics/2-streams.md'
    - 'What is an Audit?': 'student-handbook/2-academics/2-audit.md'
    - 'Understanding Your Standing': 'student-handbook/2-academics/2-standing.md'
    - 'The Hard Ones: Traditionally Difficult Courses': 'student-handbook/2-academics/2-hard-courses.md'
    - 'Group Work': 'student-handbook/2-academics/2-group.md'
    - 'Top Five Study Spots': 'student-handbook/2-academics/2-study-spots.md'
  - Social:
    - 'Top Five Food Spots': 'student-handbook/3-social/3-food-spots.md'
    - 'Ottawa is Weird': 'student-handbook/3-social/3-ottawa-is-weird.md'
  - Careers:
    - 'Co-op (Not the Gaming Kind)': 'student-handbook/4-careers/4-coop.md'
    - 'Coding Interviews': 'student-handbook/4-careers/4-coding-interviews.md'
    - 'No Really, Just Apply': 'student-handbook/4-careers/4-just-apply.md'
  - CCSS: 'student-handbook/5-ccss/index.md'
  - Technical:
    - 'Your Text Editor is Your Best Friend (and so is Coffee)': 'student-handbook/6-technical/6-text-editors-and-coffee.md'
    - 'Version Control (Like, v0.1?)': 'student-handbook/6-technical/6-version-control.md'
extra:
  base_url: /docs
