site_name: Carleton Computer Science Society Documentation
site_author: Carleton Computer Science Society
pages:
- ['test-article-1.md', 'Test-1']
- ['test-directory/test-article-2', 'Test-2', 'Part 1']
theme: readthedocs
